# Dragons App
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
# -----------------------
Parameters:
# -----------------------
  BucketNamePrefix:
    Type: String
    Default: dragon-sample-data
# -----------------------
Resources:
# -----------------------
  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dragon_data_bucket_name
      Type: String
      Value: !Sub "${BucketNamePrefix}-495-117"
      Description: Dragon bucket name
      Tags:
        Environment: DEV
  FileNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: dragon_data_file_name
      Type: String
      Value: DragonData.json
      Description: Dragon data file name
      Tags:
        Environment: DEV
 # -----------------------
  MainDragon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: MainDragon/.
      MemorySize: 128
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
# -----------------------
  ValidateDragon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ValidateDragon/.
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
# -----------------------
  AddDragon:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: AddDragon/.
      MemorySize: 128
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
# -----------------------
  ListDragons:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ListDragons/.
      MemorySize: 128
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
# -----------------------
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-python-lib
      Description: Dependencies for the blank-python sample app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.9
# -----------------------
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation template
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-495-117"
    